### ISSUE TITLE
Dupe Bug with Lava Sponge

### ISSUE THREAD

**Issue by znxster** [iamshift/MineAddons#1]
I managed to accidentally dupe a lava sponge. After a bit of trial and error I have worked out a way to consistently dupe them.

Playing on FC2 pack v2.6 which contains Mine Addons v1.3.1

- Create 2 lava sponges.
- Use both to get wet lava sponge.
- Place first wet sponge on lip of block adjacent to water pool, hanging over the edge of the water.
- Throw second into water
- The result is two wet sponges and one dried lava sponge.

I guess the wet sponge is considered to have hit both the water and collected with the one of the lip.

Thanks for the fun additions!

**Comment by shiftthedev** [comment]
should be solved in 1.3.3
